/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Assignment;

import javax.swing.JFileChooser;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.ui.ApplicationFrame;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author OCC9-02
 */
public class OutputDIsplay extends javax.swing.JFrame {

    /**
     * Creates new form Assignment
     */
    public OutputDIsplay() {
        initComponents();
    }
    

    //declare stATIc so that it can be accesed throughout the class
    static String filePath; //location of the file
    
    static Assignment analyzer;
    //create instance of the Assignment class
    //use static so that all the methods can access it without needs to create new obj 
    //in every method, just call analyzer. gitu je. 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        FileChooser = new javax.swing.JButton();
        JobPartition = new javax.swing.JButton();
        JobNumber = new javax.swing.JButton();
        Statistics = new javax.swing.JButton();
        JobCreated = new javax.swing.JButton();
        MainTab = new javax.swing.JTabbedPane();
        TabFileChooser = new javax.swing.JPanel();
        jLabelFC = new javax.swing.JLabel();
        ChooseFileButton = new javax.swing.JButton();
        TabJobDone = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Back3 = new javax.swing.JButton();
        TabStatistic = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PieJobPartition = new javax.swing.JButton();
        PieJobDone = new javax.swing.JButton();
        TabEPYC = new javax.swing.JPanel();
        Back1 = new javax.swing.JButton();
        LabelEPYC = new javax.swing.JLabel();
        TabJobPartition = new javax.swing.JPanel();
        epyc = new javax.swing.JButton();
        Opteron = new javax.swing.JButton();
        GPU_Titan = new javax.swing.JButton();
        GPU_v100s = new javax.swing.JButton();
        GPU_k40c = new javax.swing.JButton();
        GPU_k10 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TabPiePartition = new javax.swing.JPanel();
        Back7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TabPieJobDone = new javax.swing.JPanel();
        Back8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        TabJobCreated = new javax.swing.JPanel();
        July = new javax.swing.JButton();
        June = new javax.swing.JButton();
        September = new javax.swing.JButton();
        August = new javax.swing.JButton();
        October = new javax.swing.JButton();
        November = new javax.swing.JButton();
        December = new javax.swing.JButton();
        TabMonth = new javax.swing.JPanel();
        LabelMonth = new javax.swing.JLabel();
        Back2 = new javax.swing.JButton();
        TabJobNumber = new javax.swing.JPanel();
        JobDOne = new javax.swing.JButton();
        JobError = new javax.swing.JButton();
        ExeTime = new javax.swing.JButton();
        JobKilled = new javax.swing.JButton();
        ProcessingTime = new javax.swing.JButton();
        TabJobError = new javax.swing.JPanel();
        JuneError = new javax.swing.JButton();
        AugustError = new javax.swing.JButton();
        JulyError = new javax.swing.JButton();
        SepError = new javax.swing.JButton();
        OctError = new javax.swing.JButton();
        NovError = new javax.swing.JButton();
        DecError = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Back4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OCC9-02 Log File Analyzer");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        FileChooser.setText("File Chooser");
        FileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileChooserActionPerformed(evt);
            }
        });

        JobPartition.setText("JobPartition");
        JobPartition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JobPartitionActionPerformed(evt);
            }
        });

        JobNumber.setText("Job Number");
        JobNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JobNumberActionPerformed(evt);
            }
        });

        Statistics.setText("Statistic");
        Statistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatisticsActionPerformed(evt);
            }
        });

        JobCreated.setText("Job Created");
        JobCreated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JobCreatedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(Statistics, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JobCreated, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JobPartition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JobNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JobPartition, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JobNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Statistics, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JobCreated, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabFileChooser.setBackground(new java.awt.Color(0, 153, 153));

        jLabelFC.setBackground(new java.awt.Color(0, 204, 204));

        ChooseFileButton.setBackground(new java.awt.Color(255, 204, 204));
        ChooseFileButton.setFont(new java.awt.Font("Imprint MT Shadow", 0, 36)); // NOI18N
        ChooseFileButton.setText("Choose File");
        ChooseFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TabFileChooserLayout = new javax.swing.GroupLayout(TabFileChooser);
        TabFileChooser.setLayout(TabFileChooserLayout);
        TabFileChooserLayout.setHorizontalGroup(
            TabFileChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabFileChooserLayout.createSequentialGroup()
                .addGroup(TabFileChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TabFileChooserLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(ChooseFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TabFileChooserLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabelFC, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        TabFileChooserLayout.setVerticalGroup(
            TabFileChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabFileChooserLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(ChooseFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFC, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        MainTab.addTab("0", TabFileChooser);

        TabJobDone.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N

        Back3.setText("Back");
        Back3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TabJobDoneLayout = new javax.swing.GroupLayout(TabJobDone);
        TabJobDone.setLayout(TabJobDoneLayout);
        TabJobDoneLayout.setHorizontalGroup(
            TabJobDoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabJobDoneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabJobDoneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Back3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        TabJobDoneLayout.setVerticalGroup(
            TabJobDoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabJobDoneLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(Back3)
                .addGap(21, 21, 21))
        );

        MainTab.addTab("1", TabJobDone);

        TabStatistic.setBackground(new java.awt.Color(255, 204, 204));

        PieJobPartition.setBackground(new java.awt.Color(102, 102, 255));
        PieJobPartition.setText("JobPartition");
        PieJobPartition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PieJobPartitionActionPerformed(evt);
            }
        });

        PieJobDone.setBackground(new java.awt.Color(153, 255, 153));
        PieJobDone.setText("JobCreated");
        PieJobDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PieJobDoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TabStatisticLayout = new javax.swing.GroupLayout(TabStatistic);
        TabStatistic.setLayout(TabStatisticLayout);
        TabStatisticLayout.setHorizontalGroup(
            TabStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabStatisticLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(PieJobPartition, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(TabStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TabStatisticLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TabStatisticLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(PieJobDone, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TabStatisticLayout.setVerticalGroup(
            TabStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabStatisticLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(TabStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PieJobPartition, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PieJobDone, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        MainTab.addTab("2", TabStatistic);

        TabEPYC.setBackground(new java.awt.Color(204, 255, 204));

        Back1.setText("Back");
        Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back1ActionPerformed(evt);
            }
        });

        LabelEPYC.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        javax.swing.GroupLayout TabEPYCLayout = new javax.swing.GroupLayout(TabEPYC);
        TabEPYC.setLayout(TabEPYCLayout);
        TabEPYCLayout.setHorizontalGroup(
            TabEPYCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabEPYCLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(LabelEPYC, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabEPYCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Back1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TabEPYCLayout.setVerticalGroup(
            TabEPYCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabEPYCLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(LabelEPYC, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(325, 325, 325)
                .addComponent(Back1)
                .addContainerGap())
        );

        MainTab.addTab("3", TabEPYC);

        TabJobPartition.setBackground(new java.awt.Color(153, 153, 255));

        epyc.setBackground(new java.awt.Color(255, 153, 153));
        epyc.setText("EPYC");
        epyc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epycActionPerformed(evt);
            }
        });

        Opteron.setBackground(new java.awt.Color(204, 255, 204));
        Opteron.setText("OPTERON");
        Opteron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpteronActionPerformed(evt);
            }
        });

        GPU_Titan.setBackground(new java.awt.Color(153, 204, 255));
        GPU_Titan.setText("GPU Titan");
        GPU_Titan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPU_TitanActionPerformed(evt);
            }
        });

        GPU_v100s.setBackground(new java.awt.Color(255, 255, 153));
        GPU_v100s.setText("GPU v100s");
        GPU_v100s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPU_v100sActionPerformed(evt);
            }
        });

        GPU_k40c.setBackground(new java.awt.Color(102, 255, 204));
        GPU_k40c.setText("GPU k40c");
        GPU_k40c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPU_k40cActionPerformed(evt);
            }
        });

        GPU_k10.setBackground(new java.awt.Color(255, 204, 102));
        GPU_k10.setText("GPU k10");
        GPU_k10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPU_k10ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel6.setText("Choose type of job partition:");

        javax.swing.GroupLayout TabJobPartitionLayout = new javax.swing.GroupLayout(TabJobPartition);
        TabJobPartition.setLayout(TabJobPartitionLayout);
        TabJobPartitionLayout.setHorizontalGroup(
            TabJobPartitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabJobPartitionLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(TabJobPartitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TabJobPartitionLayout.createSequentialGroup()
                        .addGroup(TabJobPartitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GPU_v100s, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(epyc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TabJobPartitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Opteron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GPU_k40c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TabJobPartitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GPU_Titan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GPU_k10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(TabJobPartitionLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        TabJobPartitionLayout.setVerticalGroup(
            TabJobPartitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabJobPartitionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TabJobPartitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epyc)
                    .addComponent(Opteron)
                    .addComponent(GPU_Titan))
                .addGap(15, 15, 15)
                .addGroup(TabJobPartitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GPU_v100s)
                    .addComponent(GPU_k40c)
                    .addComponent(GPU_k10))
                .addContainerGap(381, Short.MAX_VALUE))
        );

        MainTab.addTab("4", TabJobPartition);

        TabPiePartition.setBackground(new java.awt.Color(153, 204, 255));

        Back7.setText("Back");
        Back7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back7ActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"EPYC", "2476"},
                {"OPTERON", "4409"},
                {"GPU TITAN", "640"},
                {"GPU v100s", "588"},
                {"GPU k40c", "295"},
                {"GPU k10", "428"}
            },
            new String [] {
                "Job Partition", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout TabPiePartitionLayout = new javax.swing.GroupLayout(TabPiePartition);
        TabPiePartition.setLayout(TabPiePartitionLayout);
        TabPiePartitionLayout.setHorizontalGroup(
            TabPiePartitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabPiePartitionLayout.createSequentialGroup()
                .addContainerGap(589, Short.MAX_VALUE)
                .addComponent(Back7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(TabPiePartitionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TabPiePartitionLayout.setVerticalGroup(
            TabPiePartitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabPiePartitionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(Back7)
                .addGap(27, 27, 27))
        );

        MainTab.addTab("5", TabPiePartition);

        TabPieJobDone.setBackground(new java.awt.Color(153, 255, 204));

        Back8.setText("Back");
        Back8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back8ActionPerformed(evt);
            }
        });

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"JUNE", "2423"},
                {"JULY", "1448"},
                {"AUGUST", "1520"},
                {"SEPTEMBER", "1377"},
                {"OCTOBER", "1866"},
                {"NOVEMBER", "1212"},
                {"DECEMBER", "706"}
            },
            new String [] {
                "Month", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout TabPieJobDoneLayout = new javax.swing.GroupLayout(TabPieJobDone);
        TabPieJobDone.setLayout(TabPieJobDoneLayout);
        TabPieJobDoneLayout.setHorizontalGroup(
            TabPieJobDoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabPieJobDoneLayout.createSequentialGroup()
                .addContainerGap(589, Short.MAX_VALUE)
                .addComponent(Back8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(TabPieJobDoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TabPieJobDoneLayout.setVerticalGroup(
            TabPieJobDoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabPieJobDoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addComponent(Back8)
                .addGap(27, 27, 27))
        );

        MainTab.addTab("6", TabPieJobDone);

        TabJobCreated.setBackground(new java.awt.Color(255, 153, 153));

        July.setBackground(new java.awt.Color(0, 255, 204));
        July.setText("July");
        July.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JulyActionPerformed(evt);
            }
        });

        June.setBackground(new java.awt.Color(255, 255, 153));
        June.setText("June");
        June.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuneActionPerformed(evt);
            }
        });

        September.setBackground(new java.awt.Color(255, 102, 255));
        September.setText("September");
        September.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeptemberActionPerformed(evt);
            }
        });

        August.setBackground(new java.awt.Color(0, 204, 204));
        August.setText("August");
        August.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AugustActionPerformed(evt);
            }
        });

        October.setBackground(new java.awt.Color(102, 102, 255));
        October.setText("October");
        October.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OctoberActionPerformed(evt);
            }
        });

        November.setBackground(new java.awt.Color(255, 255, 255));
        November.setText("November");
        November.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovemberActionPerformed(evt);
            }
        });

        December.setBackground(new java.awt.Color(102, 255, 102));
        December.setText("December");
        December.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TabJobCreatedLayout = new javax.swing.GroupLayout(TabJobCreated);
        TabJobCreated.setLayout(TabJobCreatedLayout);
        TabJobCreatedLayout.setHorizontalGroup(
            TabJobCreatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabJobCreatedLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(TabJobCreatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(July, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(June, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TabJobCreatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(September, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(August, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TabJobCreatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(November, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(October, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(December)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        TabJobCreatedLayout.setVerticalGroup(
            TabJobCreatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabJobCreatedLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(TabJobCreatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(August)
                    .addComponent(June)
                    .addComponent(October)
                    .addComponent(December))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TabJobCreatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(July)
                    .addComponent(September)
                    .addComponent(November))
                .addContainerGap(334, Short.MAX_VALUE))
        );

        MainTab.addTab("7", TabJobCreated);

        TabMonth.setBackground(new java.awt.Color(204, 255, 102));

        LabelMonth.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N

        Back2.setText("Back");
        Back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TabMonthLayout = new javax.swing.GroupLayout(TabMonth);
        TabMonth.setLayout(TabMonthLayout);
        TabMonthLayout.setHorizontalGroup(
            TabMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabMonthLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(LabelMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabMonthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Back2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        TabMonthLayout.setVerticalGroup(
            TabMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabMonthLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(LabelMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(Back2)
                .addGap(23, 23, 23))
        );

        MainTab.addTab("8", TabMonth);

        TabJobNumber.setBackground(new java.awt.Color(204, 255, 102));

        JobDOne.setBackground(new java.awt.Color(204, 255, 204));
        JobDOne.setText("Job Done");
        JobDOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JobDOneActionPerformed(evt);
            }
        });

        JobError.setBackground(new java.awt.Color(255, 102, 102));
        JobError.setText("Job Error");
        JobError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JobErrorActionPerformed(evt);
            }
        });

        ExeTime.setBackground(new java.awt.Color(0, 255, 51));
        ExeTime.setText("Exe Time");
        ExeTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExeTimeActionPerformed(evt);
            }
        });

        JobKilled.setBackground(new java.awt.Color(102, 204, 255));
        JobKilled.setText("Job Killed");
        JobKilled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JobKilledActionPerformed(evt);
            }
        });

        ProcessingTime.setBackground(new java.awt.Color(255, 0, 255));
        ProcessingTime.setText("Processing Time");
        ProcessingTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessingTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TabJobNumberLayout = new javax.swing.GroupLayout(TabJobNumber);
        TabJobNumber.setLayout(TabJobNumberLayout);
        TabJobNumberLayout.setHorizontalGroup(
            TabJobNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabJobNumberLayout.createSequentialGroup()
                .addGroup(TabJobNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TabJobNumberLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(JobDOne)
                        .addGap(18, 18, 18)
                        .addComponent(JobError, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JobKilled))
                    .addGroup(TabJobNumberLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(ExeTime, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ProcessingTime, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        TabJobNumberLayout.setVerticalGroup(
            TabJobNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabJobNumberLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(TabJobNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JobDOne)
                    .addComponent(JobError)
                    .addComponent(JobKilled))
                .addGap(28, 28, 28)
                .addGroup(TabJobNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProcessingTime)
                    .addComponent(ExeTime))
                .addContainerGap(365, Short.MAX_VALUE))
        );

        MainTab.addTab("9", TabJobNumber);

        TabJobError.setBackground(new java.awt.Color(255, 153, 153));

        JuneError.setText("JUNE");
        JuneError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuneErrorActionPerformed(evt);
            }
        });

        AugustError.setText("AUGUST");
        AugustError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AugustErrorActionPerformed(evt);
            }
        });

        JulyError.setText("JULY");
        JulyError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JulyErrorActionPerformed(evt);
            }
        });

        SepError.setText("SEPTEMBER");
        SepError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SepErrorActionPerformed(evt);
            }
        });

        OctError.setText("OCTOBER");
        OctError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OctErrorActionPerformed(evt);
            }
        });

        NovError.setText("NOVEMBER");
        NovError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovErrorActionPerformed(evt);
            }
        });

        DecError.setText("DECEMBER");
        DecError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecErrorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TabJobErrorLayout = new javax.swing.GroupLayout(TabJobError);
        TabJobError.setLayout(TabJobErrorLayout);
        TabJobErrorLayout.setHorizontalGroup(
            TabJobErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabJobErrorLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(TabJobErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JulyError, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JuneError, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(TabJobErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(TabJobErrorLayout.createSequentialGroup()
                        .addComponent(AugustError, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(OctError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(TabJobErrorLayout.createSequentialGroup()
                        .addComponent(SepError)
                        .addGap(18, 18, 18)
                        .addComponent(NovError)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DecError)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        TabJobErrorLayout.setVerticalGroup(
            TabJobErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabJobErrorLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(TabJobErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JuneError)
                    .addComponent(AugustError)
                    .addComponent(OctError)
                    .addComponent(DecError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TabJobErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JulyError)
                    .addComponent(SepError)
                    .addComponent(NovError))
                .addContainerGap(342, Short.MAX_VALUE))
        );

        MainTab.addTab("10", TabJobError);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        Back4.setText("Back");
        Back4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(Back4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Back4)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        MainTab.addTab("11", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainTab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JobPartitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobPartitionActionPerformed
        // TODO add your handling code here:
       MainTab.setSelectedIndex(4);
       
       
       //jLabel1.setVisible(true);
       
    }//GEN-LAST:event_JobPartitionActionPerformed

    private void JobCreatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobCreatedActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(7);
        
    }//GEN-LAST:event_JobCreatedActionPerformed

    private void StatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatisticsActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(2);
        
        
    }//GEN-LAST:event_StatisticsActionPerformed

    private void epycActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epycActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(3);
        LabelEPYC.setVisible(true);
        LabelEPYC.setText("Total Jobs of CPU EPYC "+analyzer.jobByPartition(1));
    }//GEN-LAST:event_epycActionPerformed

    private void OpteronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpteronActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(3);
        LabelEPYC.setVisible(true);
        LabelEPYC.setText("Total Jobs of CPU Opteron "+analyzer.jobByPartition(2));
    }//GEN-LAST:event_OpteronActionPerformed

    private void GPU_TitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPU_TitanActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(3);
        LabelEPYC.setVisible(true);
        LabelEPYC.setText("Total Jobs of GPU Titan "+analyzer.jobByPartition(3));
    }//GEN-LAST:event_GPU_TitanActionPerformed

    private void GPU_v100sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPU_v100sActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(3);
        LabelEPYC.setVisible(true);
        LabelEPYC.setText("Total Jobs of GPU V100s "+analyzer.jobByPartition(4));
    }//GEN-LAST:event_GPU_v100sActionPerformed

    private void GPU_k40cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPU_k40cActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(3);
        LabelEPYC.setVisible(true);
        LabelEPYC.setText("Total Jobs of GPU K40c "+analyzer.jobByPartition(5));
    }//GEN-LAST:event_GPU_k40cActionPerformed

    private void GPU_k10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPU_k10ActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(3);
        LabelEPYC.setVisible(true);
        LabelEPYC.setText("Total Jobs of GPU K10 "+analyzer.jobByPartition(6));
    }//GEN-LAST:event_GPU_k10ActionPerformed

    private void Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back1ActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(4);
    }//GEN-LAST:event_Back1ActionPerformed

    private void FileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileChooserActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(0);
    }//GEN-LAST:event_FileChooserActionPerformed

    private void ChooseFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseFileButtonActionPerformed
        // TODO add your handling code here:
        //create a file chooser 
        JFileChooser fileChooser= new JFileChooser();
        
        //open dialog
        fileChooser.showOpenDialog(jLabelFC);
        
        //retrieve the path
        filePath= fileChooser.getSelectedFile().getAbsolutePath();
        
        //create instance/obj of Assignment
        analyzer= new Assignment(filePath);
        
        jLabelFC.setVisible(true);
        jLabelFC.setText(filePath); //show the file path on the GUI
    }//GEN-LAST:event_ChooseFileButtonActionPerformed

    private void PieJobPartitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PieJobPartitionActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(5);
        Pie demo = new Pie( "Job by Partition" );  
        demo.setSize( 560 , 367 );    
        RefineryUtilities.centerFrameOnScreen( demo );    
        demo.setVisible( true );
    }//GEN-LAST:event_PieJobPartitionActionPerformed

    private void PieJobDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PieJobDoneActionPerformed
        // TODO add your handling code here:\
        MainTab.setSelectedIndex(6);
        Pie2 demo = new Pie2( "Job Created" );  
        demo.setSize( 560 , 367 );    
        RefineryUtilities.centerFrameOnScreen( demo );    
        demo.setVisible( true );
    }//GEN-LAST:event_PieJobDoneActionPerformed

    private void Back7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back7ActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(2);
    }//GEN-LAST:event_Back7ActionPerformed

    private void Back8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back8ActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(2);
    }//GEN-LAST:event_Back8ActionPerformed

    private void JobNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobNumberActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(9);
       
    }//GEN-LAST:event_JobNumberActionPerformed

    private void OctoberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OctoberActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(8);
        LabelMonth.setVisible(true);
        LabelMonth.setText("Total Job Created: "+analyzer.jobCreated("2022-10-01T00:39:18.383","2022-10-31T23:53:55.406"));
    }//GEN-LAST:event_OctoberActionPerformed

    private void JuneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuneActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(8);
        LabelMonth.setVisible(true);
        LabelMonth.setText("Total Job Created: "+analyzer.jobCreated("2022-06-01T01:02:35.148","2022-06-30T23:53:58.736"));
    }//GEN-LAST:event_JuneActionPerformed

    private void JulyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JulyActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(8);
        LabelMonth.setVisible(true);
        LabelMonth.setText("Total Job Created: "+analyzer.jobCreated("2022-07-01T00:13:16.699","2022-07-31T18:47:50.642"));
    }//GEN-LAST:event_JulyActionPerformed

    private void AugustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AugustActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(8);
        LabelMonth.setVisible(true);
        LabelMonth.setText("Total Job Created: "+analyzer.jobCreated("2022-08-01T09:39:22.452","2022-08-31T23:45:02.987"));
    }//GEN-LAST:event_AugustActionPerformed

    private void SeptemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeptemberActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(8);
        LabelMonth.setVisible(true);
        LabelMonth.setText("Total Job Created: "+analyzer.jobCreated("2022-09-01T00:11:57.866","2022-09-30T23:38:40.155"));
    }//GEN-LAST:event_SeptemberActionPerformed

    private void NovemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovemberActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(8);
        LabelMonth.setVisible(true);
        LabelMonth.setText("Total Job Created: "+analyzer.jobCreated("2022-11-01T00:30:02.035","2022-11-30T22:48:21.825"));
    }//GEN-LAST:event_NovemberActionPerformed

    private void DecemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecemberActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(8);
        LabelMonth.setVisible(true);
        LabelMonth.setText("Total Job Created: "+analyzer.jobCreated("2022-12-01T00:56:52.045","2022-12-16T14:55:46.311")); 
    }//GEN-LAST:event_DecemberActionPerformed

    private void Back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back2ActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(7);
    }//GEN-LAST:event_Back2ActionPerformed

    private void ExeTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExeTimeActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(1);
        jLabel3.setVisible(true);
        
        analyzer.jobCreated(); //store the job ID
        
        jLabel3.setText(analyzer.displayExeTime()); //display on the screen
    }//GEN-LAST:event_ExeTimeActionPerformed

    private void JobKilledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobKilledActionPerformed
        // TODO add your handling code here:
         MainTab.setSelectedIndex(1);
        jLabel3.setVisible(true);
        jLabel3.setText(analyzer.jobKilled());
    }//GEN-LAST:event_JobKilledActionPerformed

    private void JobDOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobDOneActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(1);
        jLabel3.setVisible(true);
        jLabel3.setText(analyzer.jobDone());
    }//GEN-LAST:event_JobDOneActionPerformed

    private void JobErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobErrorActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(10);
        
        
    }//GEN-LAST:event_JobErrorActionPerformed

    private void Back3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back3ActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(9);
    }//GEN-LAST:event_Back3ActionPerformed

    private void JuneErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuneErrorActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(11);
        
        System.out.println("Month: June");
        System.out.println("-----------------------------------");
        
        jLabel1.setVisible(true);
        jLabel1.setText(analyzer.jobCausingError("2022-06-01T01:02:35.148","2022-06-30T23:53:58.736"));
    }//GEN-LAST:event_JuneErrorActionPerformed

    private void JulyErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JulyErrorActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(11);
        
         System.out.println("Month: July");
        System.out.println("-----------------------------------");
        
        jLabel1.setVisible(true);
        jLabel1.setText(analyzer.jobCausingError("2022-07-01T00:13:16.699","2022-07-31T18:47:50.642"));
    }//GEN-LAST:event_JulyErrorActionPerformed

    private void AugustErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AugustErrorActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(11);
        
        System.out.println("Month: August");
        System.out.println("-----------------------------------");
        
        jLabel1.setVisible(true);
        jLabel1.setText(analyzer.jobCausingError("2022-08-01T09:39:22.452","2022-08-31T23:45:02.987"));
    }//GEN-LAST:event_AugustErrorActionPerformed

    private void SepErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SepErrorActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(11);
        
        System.out.println("Month: September");
        System.out.println("-----------------------------------");
        
        jLabel1.setVisible(true);
        jLabel1.setText(analyzer.jobCausingError("2022-09-01T00:11:57.866","2022-09-30T23:38:40.155"));
    }//GEN-LAST:event_SepErrorActionPerformed

    private void OctErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OctErrorActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(11);
        
        System.out.println("Month: October");
        System.out.println("-----------------------------------");
        
        jLabel1.setVisible(true);
        jLabel1.setText(analyzer.jobCausingError("2022-10-01T00:39:18.383","2022-10-31T23:53:55.406"));
    }//GEN-LAST:event_OctErrorActionPerformed

    private void NovErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovErrorActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(11);
        
        System.out.println("Month: November");
        System.out.println("-----------------------------------");
        
        jLabel1.setVisible(true);
        jLabel1.setText(analyzer.jobCausingError("2022-11-01T00:30:02.035","2022-11-30T22:48:21.825"));
        
        
        
    }//GEN-LAST:event_NovErrorActionPerformed

    private void DecErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecErrorActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(11);
        
        System.out.println("Month: December");
        System.out.println("-----------------------------------");
        
        jLabel1.setVisible(true);
        jLabel1.setText(analyzer.jobCausingError("2022-12-01T00:56:52.045","2022-12-16T14:55:46.311"));
    }//GEN-LAST:event_DecErrorActionPerformed

    private void Back4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back4ActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(10);
    }//GEN-LAST:event_Back4ActionPerformed

    private void ProcessingTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessingTimeActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(1);
        jLabel3.setVisible(true);
        
        jLabel3.setText(analyzer.aveProcessingTime()); //display on the screen
    }//GEN-LAST:event_ProcessingTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutputDIsplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutputDIsplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutputDIsplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutputDIsplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutputDIsplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton August;
    private javax.swing.JButton AugustError;
    private javax.swing.JButton Back1;
    private javax.swing.JButton Back2;
    private javax.swing.JButton Back3;
    private javax.swing.JButton Back4;
    private javax.swing.JButton Back7;
    private javax.swing.JButton Back8;
    private javax.swing.JButton ChooseFileButton;
    private javax.swing.JButton DecError;
    private javax.swing.JButton December;
    private javax.swing.JButton ExeTime;
    private javax.swing.JButton FileChooser;
    private javax.swing.JButton GPU_Titan;
    private javax.swing.JButton GPU_k10;
    private javax.swing.JButton GPU_k40c;
    private javax.swing.JButton GPU_v100s;
    private javax.swing.JButton JobCreated;
    private javax.swing.JButton JobDOne;
    private javax.swing.JButton JobError;
    private javax.swing.JButton JobKilled;
    private javax.swing.JButton JobNumber;
    private javax.swing.JButton JobPartition;
    private javax.swing.JButton July;
    private javax.swing.JButton JulyError;
    private javax.swing.JButton June;
    private javax.swing.JButton JuneError;
    private javax.swing.JLabel LabelEPYC;
    private javax.swing.JLabel LabelMonth;
    private javax.swing.JTabbedPane MainTab;
    private javax.swing.JButton NovError;
    private javax.swing.JButton November;
    private javax.swing.JButton OctError;
    private javax.swing.JButton October;
    private javax.swing.JButton Opteron;
    private javax.swing.JButton PieJobDone;
    private javax.swing.JButton PieJobPartition;
    private javax.swing.JButton ProcessingTime;
    private javax.swing.JButton SepError;
    private javax.swing.JButton September;
    private javax.swing.JButton Statistics;
    private javax.swing.JPanel TabEPYC;
    private javax.swing.JPanel TabFileChooser;
    private javax.swing.JPanel TabJobCreated;
    private javax.swing.JPanel TabJobDone;
    private javax.swing.JPanel TabJobError;
    private javax.swing.JPanel TabJobNumber;
    private javax.swing.JPanel TabJobPartition;
    private javax.swing.JPanel TabMonth;
    private javax.swing.JPanel TabPieJobDone;
    private javax.swing.JPanel TabPiePartition;
    private javax.swing.JPanel TabStatistic;
    private javax.swing.JButton epyc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelFC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
